services:
    laravel.test:
        build:
            context: ./.devcontainer/vendor-example/laravel/sail/runtimes/8.3
            dockerfile: Dockerfile
            args:
                WWWGROUP: "${WWWGROUP}"
        image: sail-8.3/app
        extra_hosts:
            - "host.docker.internal:host-gateway"
        ports:
            - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
        environment:
            WWWUSER: "${WWWUSER}"
            LARAVEL_SAIL: 1
            XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
            XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
            IGNITION_LOCAL_SITES_PATH: "${PWD}"
        volumes:
            - ".:/var/www/html"
            - "../../proto_files:/proto_files"
        networks:
            - sail
        depends_on:
            - redis
        labels:
            - "traefik.enable=true"
            - "traefik.http.routers.laravel.entrypoints=websecure"
            - "traefik.http.routers.laravel.tls=true"
            - "traefik.http.routers.laravel.rule=Host(`front.sacre-tech.local`)"
            - "traefik.http.routers.laravel.service=laravel"
            - "traefik.http.services.laravel.loadbalancer.server.port=8199"
    redis:
        image: "redis:alpine"
        ports:
            - "${FORWARD_REDIS_PORT:-6379}:6379"
        volumes:
            - "sail-redis:/data"
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - redis-cli
                - ping
            retries: 3
            timeout: 5s
networks:
    sail:
        driver: bridge
    default:
        name: sacre_tech
        external: true

volumes:
    sail-redis:
        driver: local
