log:
  level: INFO

api:
  insecure: true
  dashboard: true

accessLog:
  filePath: /var/log/traefik/log/access.log
  bufferingSize: 100 # Flushes the buffer every 100 lines. Improve performance by reducing disk I/O operations.

providers:
  docker:
    exposedByDefault: false
    watch: true
  file:
    filename: /etc/traefik/certificates.yml

entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
  websecure:
    address: ":443"
  grpc:
    address: ":9001"

certificatesResolvers:
  stagingResolver:
    acme:
      email: "noreply@sacret-tech.fr"
      storage: "/letsencrypt/acme.json"
      httpChallenge:
        entryPoint: web
